#!/usr/bin/env python3
"""Bootstrap generator: creates the 55 initial legacy function YAML records.

This is a one-time scaffold tool. The generated YAML files are then the
canonical editable source of truth; regenerate index files with
`scripts/ocf.py build-index` instead of re-running this script.

Data source: the OCF bootstrap specification (legacy factual mapping).
Any field that cannot be established is left as pending-source-review / null.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from ocf_tools.utils import (  # noqa: E402
    current_date,
    write_text_atomic,
    yaml_safe_dump,  # noqa: E402
)

REPO = Path(__file__).resolve().parents[2]

DOMAIN_DIR = {
    "foundation": "foundation",
    "cognition": "cognition",
    "emotion": "emotion",
    "communication": "communication",
    "body": "body",
    "performance": "performance",
    "sensory": "sensory",
    "sleep": "sleep",
    "lifestyle": "lifestyle",
    "emergency": "emergency",
    "automation": "automation",
    "experimental": "experimental",
}

# id, slug, canonical name, primary cmd, modes, legacy name, legacy commands,
# cmd_status, cmd_review, compat, availability, domain, secondary, persistence,
# safety_level, medical, evidence, rationale, summary
E = [
    # -- 39 with legacy/reference material available -------------------------
    (
        "OCF-FND-001",
        "energize",
        "Access to Energy",
        "PLUS-ENERGIZE",
        [],
        "ACCESS TO ENERGY",
        ["PLUS-ENERGIZE"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "foundation",
        ["performance"],
        "temporary",
        "general",
        False,
        "source-described",
        None,
        "Restores a felt sense of available energy on demand.",
    ),
    (
        "OCF-COG-001",
        "access-to-information",
        "Access to Information",
        "PLUS-RETRIEVE",
        [],
        "ACCESS TO INFORMATION",
        ["PLUS-RETRIEVE"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "cognition",
        ["experimental"],
        "temporary",
        "general",
        False,
        "source-described",
        None,
        "Accesses intuition, memory, and inner knowledge on demand.",
    ),
    (
        "OCF-FND-002",
        "attention",
        "Attention",
        "PLUS-FOCUS",
        [],
        "ATTENTION",
        ["PLUS-FOCUS"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "foundation",
        ["cognition"],
        "temporary",
        "general",
        False,
        "source-described",
        None,
        "Directs and sustains focused attention.",
    ),
    (
        "OCF-BOD-001",
        "brain-repairs",
        "Brain: Repairs & Maintenance",
        "PLUS-FLOW BETTER",
        [],
        "BRAIN: REPAIRS & MAINTENANCE",
        ["PLUS-FLOW BETTER"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "body",
        ["foundation"],
        "permanent",
        "health",
        True,
        "source-described",
        None,
        "Self-directed wellness practice supporting a felt sense of comfortable, balanced brain function.",
    ),
    (
        "OCF-COG-002",
        "buy-the-numbers",
        "Buy the Numbers",
        "PLUS-CALCULATE",
        [],
        "BUY THE NUMBERS",
        ["PLUS-CALCULATE"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "cognition",
        [],
        "permanent",
        "general",
        False,
        "source-described",
        None,
        "Speeds mental arithmetic and number processing.",
    ),
    (
        "OCF-BOD-002",
        "circulation",
        "Circulation",
        "PLUS-FLOW SMOOTH",
        [],
        "CIRCULATION",
        ["PLUS-FLOW SMOOTH"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "body",
        ["foundation"],
        "permanent",
        "health",
        True,
        "source-described",
        None,
        "Promotes a felt sense of smooth, comfortable circulation.",
    ),
    (
        "OCF-COG-003",
        "contemplation",
        "Contemplation",
        "PLUS-OPEN",
        ["PLUS-CLOSED"],
        "CONTEMPLATION",
        ["PLUS-OPEN", "PLUS-CLOSED"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "cognition",
        [],
        "temporary",
        "general",
        False,
        "source-described",
        None,
        "Opens an internal space for quiet reflection; closes it again on completion.",
    ),
    (
        "OCF-BOD-003",
        "de-discomfort",
        "De-Discomfort",
        "PLUS-COMFORT",
        [],
        "DE-DISCOMFORT",
        ["PLUS-55515"],
        "proposed",
        "review-required",
        "bridge-trainable",
        "available",
        "body",
        [],
        "temporary",
        "health",
        True,
        "community-hypothesis",
        "The legacy numeric cue (PLUS-55515) is cryptic; the concise OCF cue PLUS-COMFORT is proposed for review.",
        "Felt-discomfort support for self-directed comfort; proposed concise cue PLUS-COMFORT.",
    ),
    (
        "OCF-LIF-001",
        "de-hab",
        "De-Hab",
        "PLUS-NO MORE, NO MORE",
        [],
        "DE-HAB",
        ["PLUS-NO MORE, NO MORE"],
        "review-required",
        "review-required",
        "bridge-trainable",
        "available",
        "lifestyle",
        ["emotion"],
        "temporary",
        "general",
        False,
        "community-hypothesis",
        "Legacy cue is four spoken words; a concise replacement requires review.",
        "Supports stepping away from habitual, repeated behavior patterns.",
    ),
    (
        "OCF-BOD-004",
        "de-tox-body",
        "De-Tox: Body",
        "PLUS-DETOX",
        [],
        "DE-TOX: BODY",
        ["PLUS-CLEAN, CLEAR"],
        "proposed",
        "review-required",
        "bridge-trainable",
        "available",
        "body",
        ["lifestyle"],
        "permanent",
        "health",
        True,
        "source-described",
        "Legacy two-phrase cue is concise already, but PLUS-DETOX is proposed as the single canonical cue for review.",
        "Supports a perceived sense of bodily cleansing and clarity.",
    ),
    (
        "OCF-PRF-001",
        "do-this-now",
        "Do This Now",
        "PLUS-DO-THIS-NOW",
        [],
        "DO THIS NOW",
        ["PLUS-DO-THIS-NOW"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "performance",
        [],
        "temporary",
        "general",
        False,
        "source-described",
        None,
        "Moves from deliberation into immediate, present action.",
    ),
    (
        "OCF-BOD-005",
        "eat-no-eat",
        "Eat/No Eat",
        "PLUS-SATISFIED, SUPPLIED",
        [],
        "EAT/NO EAT",
        ["PLUS-SATISFIED, SUPPLIED"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "body",
        ["lifestyle"],
        "temporary",
        "health",
        True,
        "source-described",
        None,
        "Adjusts appetite signals in either direction.",
    ),
    (
        "OCF-PRF-002",
        "eight-great",
        "Eight-Great",
        "PLUS-STRONG",
        [],
        "EIGHT-GREAT",
        ["PLUS-EIGHT, GREAT"],
        "proposed",
        "review-required",
        "bridge-trainable",
        "available",
        "performance",
        ["body"],
        "permanent",
        "general",
        False,
        "community-hypothesis",
        "Legacy cue PLUS-EIGHT, GREAT is two words; concise cue PLUS-STRONG is proposed for review.",
        "Legacy vitality practice associated with the phrase EIGHT, GREAT; proposed concise cue PLUS-STRONG.",
    ),
    (
        "OCF-BOD-006",
        "heart-repairs",
        "Heart: Repairs & Maintenance",
        "PLUS-HEART, BETTER, BETTER",
        [],
        "HEART: REPAIRS & MAINTENANCE",
        ["PLUS-HEART, BETTER, BETTER"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "body",
        [],
        "permanent",
        "health",
        True,
        "source-described",
        None,
        "Self-directed wellness practice supporting a felt sense of calm, steady heart function.",
    ),
    (
        "OCF-BOD-007",
        "hypertension",
        "Hypertension",
        "PLUS-BALANCE-BLOODPRESSURE",
        [],
        "HYPERTENSION",
        ["PLUS-BALANCE-BLOODPRESSURE"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "body",
        [],
        "temporary",
        "health",
        True,
        "source-described",
        None,
        "Legacy practice associated with blood-pressure balance. Not a treatment and not a substitute for medical care.",
    ),
    (
        "OCF-BOD-008",
        "immunizing",
        "Immunizing",
        "PLUS-ALERT, DESTROY",
        [],
        "IMMUNIZING",
        ["PLUS-ALERT, DESTROY"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "body",
        [],
        "permanent",
        "health",
        True,
        "source-described",
        None,
        "Supports a felt sense of alertness and preparedness; not a medical claim.",
    ),
    (
        "OCF-COG-004",
        "imprint",
        "Imprint",
        "PLUS-IMPRINT",
        ["PLUS-RECALL"],
        "IMPRINT",
        ["PLUS-IMPRINT, IMPRINT", "PLUS-RECALL"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "cognition",
        [],
        "temporary",
        "general",
        False,
        "source-described",
        None,
        "Imprints a chosen suggestion or intention using the IMPRINT rehearsal.",
    ),
    (
        "OCF-EMO-001",
        "let-go",
        "Let Go",
        "PLUS-LET GO",
        [],
        "LET GO",
        ["PLUS-LET GO"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "emotion",
        ["foundation"],
        "temporary",
        "general",
        False,
        "source-described",
        None,
        "Releases clinging, tension, or unwanted mental objects.",
    ),
    (
        "OCF-BOD-009",
        "lungs-repairs",
        "Lungs: Repairs & Maintenance",
        "PLUS-BREATH BETTER",
        [],
        "LUNGS: REPAIRS & MAINTENANCE",
        ["PLUS-BREATH BETTER"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "body",
        [],
        "permanent",
        "health",
        True,
        "source-described",
        None,
        "Self-directed wellness practice supporting easy, comfortable breathing.",
    ),
    (
        "OCF-EXP-001",
        "mobius-west",
        "Mobius West",
        "PLUS-PROGRAM",
        [],
        "MOBIUS WEST",
        ["PLUS-CHANGE, CHANGE"],
        "proposed",
        "review-required",
        "bridge-trainable",
        "available",
        "experimental",
        ["foundation"],
        "temporary",
        "general",
        False,
        "community-hypothesis",
        "Legacy two-word cue PLUS-CHANGE, CHANGE is retained; concise cue PLUS-PROGRAM is proposed for review.",
        "Legacy 'change' practice for breaking personal loops; proposed concise cue PLUS-PROGRAM.",
    ),
    (
        "OCF-BOD-010",
        "nutricia",
        "Nutricia",
        "PLUS-FOOD MORE",
        ["PLUS-FOOD LESS"],
        "NUTRICIA",
        ["PLUS-FOOD MORE", "PLUS-FOOD LESS"],
        "normalized",
        "needs-review",
        "alias-listed",
        "available",
        "body",
        ["lifestyle"],
        "temporary",
        "health",
        True,
        "community-hypothesis",
        "Vocabulary normalization: food-direction magnitudes stay MORE/LESS per the OCF grammar.",
        "Adjusts appetite and food drive in either direction using the MORE/LESS grammar.",
    ),
    (
        "OCF-EMO-002",
        "off-loading",
        "Off-Loading",
        "PLUS-CLEAR",
        [],
        "OFF-LOADING",
        ["PLUS-FADE, FADE"],
        "proposed",
        "review-required",
        "bridge-trainable",
        "available",
        "emotion",
        ["foundation"],
        "temporary",
        "general",
        False,
        "community-hypothesis",
        "Legacy two-word cue PLUS-FADE, FADE is retained; concise cue PLUS-CLEAR is proposed for review.",
        "Fades and off-loads unhelpful mental load or charge; proposed concise cue PLUS-CLEAR.",
    ),
    (
        "OCF-COG-005",
        "options",
        "Options",
        "PLUS-OPTIONS",
        [],
        "OPTIONS",
        ["PLUS-OPTIONS, CHOICES"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "cognition",
        [],
        "temporary",
        "general",
        False,
        "source-described",
        None,
        "Opens perception of choices and alternatives.",
    ),
    (
        "OCF-BOD-011",
        "passages",
        "Passages",
        "PLUS-EQUALIZE-HARMONIZE",
        [],
        "PASSAGES",
        ["PLUS-EQUALIZE-HARMONIZE"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "body",
        ["lifestyle"],
        "temporary",
        "general",
        False,
        "source-described",
        None,
        "Supports graceful passage through internal transitions.",
    ),
    (
        "OCF-COG-006",
        "recall",
        "Recall",
        "PLUS-RECALL",
        [],
        "RECALL",
        ["PLUS-RECALL"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "cognition",
        [],
        "temporary",
        "general",
        False,
        "source-described",
        None,
        "Brings specific memories or learned material to mind on request.",
    ),
    (
        "OCF-FND-003",
        "recharge",
        "Recharge",
        "PLUS-RECHARGE",
        [],
        "RECHARGE",
        ["PLUS-RECHARGE"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "foundation",
        ["body"],
        "temporary",
        "general",
        False,
        "source-described",
        None,
        "Replenishes a felt sense of energy and freshness.",
    ),
    (
        "OCF-FND-004",
        "relax",
        "Relax",
        "PLUS-RELAX",
        [],
        "RELAX",
        ["PLUS-RELAX, RELAX"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "foundation",
        ["body"],
        "temporary",
        "general",
        False,
        "source-described",
        None,
        "Deepens physical and mental relaxation.",
    ),
    (
        "OCF-FND-005",
        "reset",
        "Reset",
        "PLUS-RESET",
        [],
        "RESET",
        ["PLUS-RESET, RESET"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "foundation",
        [],
        "temporary",
        "general",
        False,
        "source-described",
        None,
        "Returns mind and body to a neutral, settled baseline.",
    ),
    (
        "OCF-SLP-001",
        "restorative-sleep",
        "Restorative Sleep",
        "PLUS-RESTORE",
        [],
        "RESTORATIVE SLEEP",
        ["PLUS-HEAL, HEAL"],
        "proposed",
        "review-required",
        "bridge-trainable",
        "available",
        "sleep",
        ["body"],
        "temporary",
        "health",
        True,
        "community-hypothesis",
        "Legacy two-word cue PLUS-HEAL, HEAL is retained; concise cue PLUS-RESTORE is proposed for review.",
        "Supports deep, restorative rest and recovery; proposed concise cue PLUS-RESTORE.",
    ),
    (
        "OCF-SEN-001",
        "hearing",
        "Sensory: Hearing",
        "PLUS-HEAR MORE",
        ["PLUS-HEAR LESS"],
        "SENSORY: HEARING",
        ["PLUS-HEAR MORE", "PLUS-HEAR LESS"],
        "normalized",
        "needs-review",
        "alias-listed",
        "available",
        "sensory",
        [],
        "temporary",
        "general",
        False,
        "community-hypothesis",
        "Vocabulary normalization: auditory magnitudes standardize on MORE/LESS.",
        "Adjusts inward listening and perception in either direction using the MORE/LESS grammar.",
    ),
    (
        "OCF-SEN-002",
        "seeing",
        "Sensory: Seeing",
        "PLUS-SEE MORE",
        ["PLUS-SEE LESS"],
        "SENSORY: SEEING",
        ["PLUS-SEE BETTER"],
        "normalized",
        "needs-review",
        "alias-listed",
        "available",
        "sensory",
        [],
        "permanent",
        "general",
        False,
        "community-hypothesis",
        "Vocabulary normalization: the permanent SEE-BETTER cue keeps its meaning; directional magnitudes standardize on MORE/LESS.",
        "Improves the felt sense of inner vision and clarity; directional magnitudes use MORE/LESS.",
    ),
    (
        "OCF-BOD-012",
        "sex-drive",
        "Sex Drive",
        "PLUS-SEX MORE",
        ["PLUS-SEX LESS"],
        "SEX DRIVE",
        ["PLUS-SEX GREATER", "PLUS-SEX LESSER"],
        "normalized",
        "needs-review",
        "alias-listed",
        "available",
        "body",
        ["sensory"],
        "temporary",
        "health",
        True,
        "community-hypothesis",
        "Vocabulary normalization: GREATER/LESSER magnitudes standardize on MORE/LESS.",
        "Adjusts felt sexual drive in either direction using the MORE/LESS grammar.",
    ),
    (
        "OCF-SLP-002",
        "sleep",
        "Sleep",
        "PLUS-SLEEP",
        [],
        "SLEEP",
        ["PLUS-20-20"],
        "proposed",
        "review-required",
        "bridge-trainable",
        "available",
        "sleep",
        [],
        "temporary",
        "general",
        False,
        "community-hypothesis",
        "Legacy numeric cue PLUS-20-20 is cryptic; concise cue PLUS-SLEEP is proposed for review.",
        "Induces a felt, deliberate movement into sleep onset; proposed concise cue PLUS-SLEEP.",
    ),
    (
        "OCF-COM-001",
        "speak-up",
        "Speak Up",
        "PLUS-SPEAK UP",
        [],
        "SPEAK UP",
        ["PLUS-SPEAK UP"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "communication",
        [],
        "permanent",
        "general",
        False,
        "source-described",
        None,
        "Supports confident, clear verbal expression.",
    ),
    (
        "OCF-SLP-003",
        "sweet-dreams",
        "Sweet Dreams",
        "PLUS-DREAM",
        [],
        "SWEET DREAMS",
        ["PLUS-THEME, DREAM, SLEEP"],
        "proposed",
        "review-required",
        "bridge-trainable",
        "available",
        "sleep",
        [],
        "temporary",
        "general",
        False,
        "community-hypothesis",
        "Legacy three-word cue PLUS-THEME, DREAM, SLEEP is retained; concise cue PLUS-DREAM is proposed for review.",
        "Sets dream themes and a restful dream-sleep mindset; proposed concise cue PLUS-DREAM.",
    ),
    (
        "OCF-PRF-003",
        "synchronizing",
        "Synchronizing",
        "PLUS-SMOOTH, FAST",
        [],
        "SYNCHRONIZING",
        ["PLUS-SMOOTH, FAST"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "performance",
        ["body"],
        "permanent",
        "general",
        False,
        "source-described",
        None,
        "Aligns and smooths internal rhythms toward feeling faster and steadier.",
    ),
    (
        "OCF-COG-007",
        "think-fast",
        "Think Fast",
        "PLUS-THINK",
        [],
        "THINK FAST",
        ["PLUS-THINK"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "cognition",
        ["performance"],
        "permanent",
        "general",
        False,
        "source-described",
        None,
        "Accelerates thinking speed and mental processing.",
    ),
    (
        "OCF-BOD-013",
        "tune-up",
        "Tune-Up",
        "PLUS-BALANCE, HEAL",
        [],
        "TUNE-UP",
        ["PLUS-BALANCE, HEAL"],
        "unchanged",
        "approved",
        "unchanged",
        "available",
        "body",
        [],
        "temporary",
        "health",
        True,
        "source-described",
        None,
        "A general self-directed balance-and-heal tune-up practice.",
    ),
    (
        "OCF-SLP-004",
        "wake-know",
        "Wake/Know",
        "PLUS-KNOW",
        [],
        "WAKE/KNOW",
        ["PLUS-SLEEP, HELP"],
        "proposed",
        "review-required",
        "bridge-trainable",
        "available",
        "sleep",
        [],
        "temporary",
        "general",
        False,
        "community-hypothesis",
        "Legacy two-word cue PLUS-SLEEP, HELP is retained; concise cue PLUS-KNOW is proposed for review.",
        "Requests help with sleep and with knowing the right time to wake; proposed concise cue PLUS-KNOW.",
    ),
    # -- 16 documented legacy functions with source material unavailable -----
    (
        "OCF-EMG-001",
        "emergency-injury",
        "Emergency: Injury",
        "PLUS-CONTROL, BALANCE, RESTORE",
        [],
        "EMERGENCY: INJURY",
        ["PLUS-CONTROL, BALANCE, RESTORE"],
        "unchanged",
        "approved",
        "unchanged",
        "unavailable",
        "emergency",
        ["foundation"],
        "temporary",
        "emergency",
        True,
        "unverified",
        None,
        "Emergency-oriented practice to stay calm and take helpful action. Does NOT replace emergency services, first aid, or professional care.",
    ),
    (
        "OCF-EMG-002",
        "emergency-toxic",
        "Emergency: Toxic",
        "PLUS-CLEAR, REMOVE",
        [],
        "EMERGENCY: TOXIC",
        ["PLUS-CLEAR, REMOVE"],
        "unchanged",
        "approved",
        "unchanged",
        "unavailable",
        "emergency",
        [],
        "temporary",
        "emergency",
        True,
        "unverified",
        None,
        "Emergency-oriented practice for toxic-exposure situations. Does NOT replace poison control, emergency services, or medical evaluation.",
    ),
    (
        "OCF-EMO-003",
        "empathizing",
        "Empathizing",
        "PLUS-PROFILE, PROFILE",
        [],
        "EMPATHIZING",
        ["PLUS-PROFILE, PROFILE"],
        "unchanged",
        "approved",
        "unchanged",
        "unavailable",
        "emotion",
        ["communication"],
        "temporary",
        "general",
        False,
        "unverified",
        None,
        "Builds a felt profile of another person's experience.",
    ),
    (
        "OCF-PRF-004",
        "light-foot",
        "Light Foot",
        "PLUS-LIGHT",
        [],
        "LIGHT FOOT",
        ["PLUS-LIGHTER, LIGHTER"],
        "proposed",
        "review-required",
        "bridge-trainable",
        "unavailable",
        "performance",
        ["body"],
        "temporary",
        "general",
        False,
        "community-hypothesis",
        "Legacy two-word cue PLUS-LIGHTER, LIGHTER is retained; concise cue PLUS-LIGHT is proposed for review.",
        "Eases the felt sense of physical lightness and ease of movement; proposed concise cue PLUS-LIGHT.",
    ),
    (
        "OCF-PRF-005",
        "make-your-day",
        "Make Your Day",
        "PLUS-THIS DAY",
        [],
        "MAKE YOUR DAY",
        ["PLUS-THIS DAY"],
        "unchanged",
        "approved",
        "unchanged",
        "unavailable",
        "performance",
        [],
        "temporary",
        "general",
        False,
        "unverified",
        None,
        "Sets a deliberate tone for the day ahead.",
    ),
    (
        "OCF-BOD-014",
        "regenerate",
        "Regenerate",
        "PLUS-REGENERATE",
        [],
        "REGENERATE",
        ["PLUS-BUILD, LIVE"],
        "proposed",
        "review-required",
        "bridge-trainable",
        "unavailable",
        "body",
        [],
        "permanent",
        "health",
        True,
        "community-hypothesis",
        "The obvious concise OCF cue PLUS-REGENERATE is proposed but explicitly marked for review, not assumed approved.",
        "Supports a felt sense of body-wide regeneration and renewal; proposed concise cue PLUS-REGENERATE for review.",
    ),
    (
        "OCF-FND-006",
        "release",
        "Release",
        "PLUS-RELEASE",
        [],
        "RELEASE",
        ["PLUS-RELEASE"],
        "unchanged",
        "approved",
        "unchanged",
        "unavailable",
        "foundation",
        [],
        "temporary",
        "general",
        False,
        "unverified",
        None,
        "Releases unhelpful states, prompts, or lingering experiences.",
    ),
    (
        "OCF-AUT-001",
        "see-be",
        "See-Be",
        "PLUS-AUTOMATE",
        [],
        "SEE-BE",
        ["PLUS-AUTOMATE"],
        "unchanged",
        "approved",
        "unchanged",
        "unavailable",
        "automation",
        [],
        "temporary",
        "general",
        False,
        "unverified",
        None,
        "Automates a desired way of being so it runs without active effort.",
    ),
    (
        "OCF-SEN-003",
        "smell",
        "Sensory: Smell",
        "PLUS-SMELL MORE",
        ["PLUS-SMELL LESS"],
        "SENSORY: SMELL",
        ["PLUS-SMELL GREATER", "PLUS-SMELL LESSER"],
        "normalized",
        "needs-review",
        "alias-listed",
        "unavailable",
        "sensory",
        [],
        "temporary",
        "general",
        False,
        "community-hypothesis",
        "Vocabulary normalization: GREATER/LESSER magnitudes standardize on MORE/LESS.",
        "Adjusts the felt sense of smell in either direction using the MORE/LESS grammar.",
    ),
    (
        "OCF-SEN-004",
        "taste",
        "Sensory: Taste",
        "PLUS-TASTE MORE",
        ["PLUS-TASTE LESS"],
        "SENSORY: TASTE",
        ["PLUS-TASTE GREATER", "PLUS-TASTE LESSER"],
        "normalized",
        "needs-review",
        "alias-listed",
        "unavailable",
        "sensory",
        [],
        "temporary",
        "general",
        False,
        "community-hypothesis",
        "Vocabulary normalization: GREATER/LESSER magnitudes standardize on MORE/LESS.",
        "Adjusts the felt sense of taste in either direction using the MORE/LESS grammar.",
    ),
    (
        "OCF-SEN-005",
        "touch",
        "Sensory: Touch",
        "PLUS-TOUCH MORE",
        ["PLUS-TOUCH LESS"],
        "SENSORY: TOUCH",
        ["PLUS-TOUCH GREATER", "PLUS-TOUCH LESSER"],
        "normalized",
        "needs-review",
        "alias-listed",
        "unavailable",
        "sensory",
        [],
        "temporary",
        "general",
        False,
        "community-hypothesis",
        "Vocabulary normalization: GREATER/LESSER magnitudes standardize on MORE/LESS.",
        "Adjusts the felt sense of touch or skin sensation using the MORE/LESS grammar.",
    ),
    (
        "OCF-BOD-015",
        "short-fix",
        "Short Fix",
        "PLUS-NUMB",
        [],
        "SHORT FIX",
        ["PLUS-GO NUMB, GO NUMB", "PLUS-RELEASE"],
        "proposed",
        "review-required",
        "bridge-trainable",
        "unavailable",
        "body",
        [],
        "temporary",
        "health",
        True,
        "community-hypothesis",
        "Legacy rapid-numbing cues are retained as aliases; concise cue PLUS-NUMB is proposed for review.",
        "Legacy rapid numbing practice (GO NUMB) with a release; proposed concise cue PLUS-NUMB.",
    ),
    (
        "OCF-SLP-005",
        "sleep-easy",
        "Sleep Easy",
        "PLUS-SLEEP EASY",
        [],
        "SLEEP EASY",
        ["PLUS-QUIET, SLEEP"],
        "proposed",
        "review-required",
        "bridge-trainable",
        "unavailable",
        "sleep",
        [],
        "temporary",
        "general",
        False,
        "community-hypothesis",
        "Legacy two-word cue PLUS-QUIET, SLEEP is retained; canonical PLUS-SLEEP EASY is proposed for review.",
        "Promotes easy, quiet transition into sleep; proposed concise cue PLUS-SLEEP EASY.",
    ),
    (
        "OCF-SLP-006",
        "stay-awake",
        "Stay Awake",
        "PLUS-AWAKE",
        [],
        "STAY AWAKE",
        ["PLUS-ONE, AWAKE, ALERT, ONE, ONE"],
        "proposed",
        "review-required",
        "bridge-trainable",
        "unavailable",
        "sleep",
        ["performance"],
        "temporary",
        "general",
        False,
        "community-hypothesis",
        "Legacy five-word cue is heavy; concise cue PLUS-AWAKE is proposed for review.",
        "Supports staying awake and alert when needed; proposed concise cue PLUS-AWAKE.",
    ),
    (
        "OCF-PRF-006",
        "strong-quick",
        "Strong-Quick",
        "PLUS-STRONG QUICK",
        [],
        "STRONG-QUICK",
        ["PLUS-STRONG-QUICK"],
        "proposed",
        "review-required",
        "bridge-trainable",
        "unavailable",
        "performance",
        ["body"],
        "temporary",
        "general",
        False,
        "community-hypothesis",
        "Hyphenated legacy cue PLUS-STRONG-QUICK reads as one word; canonical PLUS-STRONG QUICK is proposed for review.",
        "Combines strength and quickness in a single felt state; proposed concise cue PLUS-STRONG QUICK.",
    ),
    (
        "OCF-EXP-002",
        "zoning",
        "Zoning",
        "PLUS-ZONE",
        ["PLUS-CANCEL"],
        "ZONING",
        ["PLUS-INSULATE, INSULATE", "PLUS-CANCEL"],
        "proposed",
        "review-required",
        "bridge-trainable",
        "unavailable",
        "experimental",
        [],
        "temporary",
        "general",
        False,
        "community-hypothesis",
        "Legacy two-word cue PLUS-INSULATE, INSULATE is retained; concise cue PLUS-ZONE (with PLUS-CANCEL) is proposed for review.",
        "Insulates against unwanted influence; cancels the zoning state via PLUS-CANCEL.",
    ),
]

HEALTH_NOTES = [
    "Self-directed wellness practice; not a substitute for professional medical evaluation or treatment. No guaranteed effects are claimed."
]
EMERGENCY_NOTES = [
    "Does NOT replace emergency services, first aid, poison control, or medical evaluation.",
    "If you believe you have an emergency or poisoning, call your local emergency number first.",
]


def build_record(e: tuple) -> dict:
    (
        ocf_id,
        slug,
        name,
        primary,
        modes,
        legacy_name,
        legacy_cmds,
        cmd_status,
        cmd_review,
        compat_state,
        availability,
        domain,
        secondary,
        persistence,
        safety_level,
        medical,
        evidence,
        rationale,
        summary,
    ) = e

    today = current_date()

    compat: dict = {"state": compat_state}
    if rationale:
        compat["rationale"] = rationale
    if cmd_status != "unchanged":
        compat["legacy_commands"] = legacy_cmds

    safety_notes: list[str] = []
    if safety_level == "health":
        safety_notes = list(HEALTH_NOTES)
    elif safety_level == "emergency":
        safety_notes = list(EMERGENCY_NOTES)

    return {
        "schema_version": "1.0",
        "id": ocf_id,
        "slug": slug,
        "contributor": {"name": None, "contact": None},
        "canonical": {
            "name": name,
            "command": {"primary": primary, "modes": list(modes)},
        },
        "legacy": {
            "source_system": "Monroe H-PLUS",
            "name": legacy_name,
            "commands": list(legacy_cmds),
            "command_status": cmd_status,
            "source_availability": availability,
        },
        "ocf": {
            "reimplementation_status": "planned",
            "command_review": cmd_review,
        },
        "aliases": {
            "names": [name],
            "commands": [c for c in legacy_cmds if c not in ([primary] + list(modes))],
        },
        "classification": {"primary_domain": domain, "secondary_domains": list(secondary)},
        "compatibility": compat,
        "status": {
            "maturity": "legacy-mapped",
            "implementation": "specification-only",
            "evidence": evidence,
        },
        "lifecycle": {
            "persistence": persistence,
            "activation": "manual",
            "trigger_conditions": [],
            "release": {"required": False, "command": None},
        },
        "purpose": {
            "summary": summary,
            "source_description": None,
            "community_description": summary,
        },
        "applications": [],
        "use_cases": [],
        "companions": [],
        "incompatible_functions": [],
        "chains": [],
        "safety": {
            "level": safety_level,
            "notes": safety_notes,
            "medical_relevance": medical,
        },
        "claims": {
            "intended_effects": [],
            "prohibited_claims": [
                "No guaranteed psychological, physiological, medical, paranormal, or behavioral result is claimed."
            ],
        },
        "audio": {
            "script_status": "not-started",
            "implementation_status": "not-started",
            "background_audio": {"strategy": "optional", "engine": "farfield", "preset": None},
        },
        "sources": [
            {
                "type": "legacy-reference",
                "title": "OCF Bootstrap Specification — Legacy Function Index",
                "locator": None,
                "url": None,
            }
        ],
        "attribution": {
            "original_authors": [],
            "ocf_contributors": [],
        },
        "version": {"current": "0.1.0", "created": today, "updated": today},
        "history": [
            {
                "version": "0.1.0",
                "date": today,
                "note": "Initial legacy mapping record created by bootstrap generator.",
            }
        ],
    }


def main() -> int:
    written = 0
    for entry in E:
        record = build_record(entry)
        target = (
            REPO
            / "functions"
            / DOMAIN_DIR[record["classification"]["primary_domain"]]
            / f"{record['slug']}.yaml"
        )
        write_text_atomic(target, yaml_safe_dump(record))
        written += 1
    print(f"Wrote {written} function records to functions/<domain>/...")
    if written != 55:
        print(f"warning: expected 55, wrote {written}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
